### ISSUE TITLE
Icon colors

### ISSUE THREAD

**Issue by atorscho** [wesselperik/nova-status-field#4]
Hi,

I just installed this package, thank you for your work by the way, and noticed that icons are not colorful:

<img width="110" alt="Screenshot 2022-05-09 at 00 28 18" src="https://user-images.githubusercontent.com/7644596/167318348-39f54b4a-cb8a-4db4-9c48-bfef7b5347e9.png">

It seems that you are using custom CSS classes, like `text-success` and `text-danger` instead of Tailwind classes.

**Comment by amharris** [comment]
@atorscho Likewise, I'm also having this issue.

Though for `pending`, that icon does display in orange, as expected; but the icons for `inactive` and `active` are grey, as you've noted.

Hopefully it'll be sorted shortly (but may throw in a PR myself, if I get a moment).

**Comment by wesselperik** [comment]
Hi @atorscho,

Good catch, didn't check this properly when upgrading the package to support Nova 4.0.

In older versions of Nova the `text-***` classes were available but it seems they removed them from the core CSS.
Will look into this soon.

**Comment by jjjrmy** [comment]
They updated to Tailwind 3.0, so now it uses different classes

**Comment by jjjrmy** [comment]
This should be fixed by PR #6

**Comment by wesselperik** [comment]
As mentioned on #6, we need to dive deeper into this and include the Tailwind colors in this package. See also [laravel/nova-issues#4061](https://github.com/laravel/nova-issues/issues/4061).

Will keep this issue open @jjjrmy because it is not fixed yet.
